-- DEPRECATED — no longer used.
-- The project now uses Neon Postgres (see DATABASE_SETUP.md). Tables are
-- created and seeded automatically by the app; no manual SQL step is needed.
-- This file is kept only so old links don't break. Safe to delete.
